config/routes.rb
Rails.application.routes.draw do
  resources :eventos

  resources :dispositivos do
     resources :eventos
  end

  resources :condominios do
     resources :dispositivos do
     resources :eventos
  end
  end

end

app/models/condominio.rb
class Condominio < ActiveRecord::Base
    has_many :dispositivos, dependent: :destroy
    validates_presence_of :nome
end

app/models/dispositivo.rb
class Dispositivo < ActiveRecord::Base
    belongs_to :condominio
    has_many :eventos, dependent: :destroy
    validates_presence_of :nome
end

app/models/evento.rb
class Evento < ActiveRecord::Base
    belongs_to :dispositivo
    validates_presence_of :mensagem_evento
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/condominios_controller.rb
class CondominiosController < ApplicationController
  before_action :set_condominio, only: [:show, :edit, :update, :destroy]

  # GET /condominios
  # GET /condominios.json
  def index
    @condominios = Condominio.all
  end

  # GET /condominios/1
  # GET /condominios/1.json
  def show
  end

  # GET /condominios/new
  def new
    @condominio = Condominio.new
  end

  # GET /condominios/1/edit
  def edit
  end

  # POST /condominios
  # POST /condominios.json
  def create
    @condominio = Condominio.new(condominio_params)

    respond_to do |format|
      if @condominio.save
        format.html { redirect_to @condominio, notice: 'Condominio was successfully created.' }
        format.json { render :show, status: :created, location: @condominio }
      else
        format.html { render :new }
        format.json { render json: @condominio.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /condominios/1
  # PATCH/PUT /condominios/1.json
  def update
    respond_to do |format|
      if @condominio.update(condominio_params)
        format.html { redirect_to @condominio, notice: 'Condominio was successfully updated.' }
        format.json { render :show, status: :ok, location: @condominio }
      else
        format.html { render :edit }
        format.json { render json: @condominio.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /condominios/1
  # DELETE /condominios/1.json
  def destroy
    @condominio.destroy
    respond_to do |format|
      format.html { redirect_to condominios_url, notice: 'Condominio was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_condominio
      @condominio = Condominio.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def condominio_params
      params.require(:condominio).permit(:nome, :lat, :long, :endereco, :bairro, :cidade, :estado, :cep, :cnpj, :numero_contrato_atual, :website)
    end
end

app/controllers/dispositivos_controller.rb
class DispositivosController < ApplicationController
  before_action :set_dispositivo, only: [:show, :edit, :update, :destroy]

  # GET /dispositivos
  # GET /dispositivos.json
  def index
    @dispositivos = Dispositivo.all
  end

  # GET /dispositivos/1
  # GET /dispositivos/1.json
  def show
  end

  # GET /dispositivos/new
  def new
    @dispositivo = Dispositivo.new
  end

  # GET /dispositivos/1/edit
  def edit
  end

  # POST /dispositivos
  # POST /dispositivos.json
  def create
    @condominio = Condominio.find(params[:condominio_id])  # linha inserida
    #@dispositivo = Dispositivo.new(dispositivo_params)    # linha anterior
    @dispositivo = @condominio.dispositivos.create(dispositivo_params) # linha alterada

    respond_to do |format|
      if @dispositivo.save
        # prox linha alterada @dispositivo para @condominio, a resp volta pag condominio
        format.html { redirect_to @condominio, notice: 'Dispositivo was successfully created.' }
        format.json { render :show, status: :created, location: @dispositivo }
      else
        format.html { render :new }
        format.json { render json: @dispositivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /dispositivos/1
  # PATCH/PUT /dispositivos/1.json
  def update
    respond_to do |format|
      if @dispositivo.update(dispositivo_params)
        format.html { redirect_to @dispositivo, notice: 'Dispositivo was successfully updated.' }
        format.json { render :show, status: :ok, location: @dispositivo }
      else
        format.html { render :edit }
        format.json { render json: @dispositivo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /dispositivos/1
  # DELETE /dispositivos/1.json
  def destroy
    @dispositivo.destroy
    respond_to do |format|
      format.html { redirect_to dispositivos_url, notice: 'Dispositivo was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_dispositivo
      @dispositivo = Dispositivo.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def dispositivo_params
      params.require(:dispositivo).permit(:condominio_id, :part_number, :nome, :fabricante, :zonas, :tipo_dispositivo, :trigger_alarme, :valor_limite_superior, :valor_limite_inferior, :ip_address_dispositivo)
    end
end

app/controllers/eventos_controller.rb
class EventosController < ApplicationController
  before_action :set_evento, only: [:show, :edit, :update, :destroy]

  # GET /eventos
  # GET /eventos.json
  def index
    @eventos = Evento.all
  end

  # GET /eventos/1
  # GET /eventos/1.json
  def show
  end

  # GET /eventos/new
  def new
    @evento = Evento.new
  end

  # GET /eventos/1/edit
  def edit
  end

  # POST /eventos
  # POST /eventos.json
  def create
    @dispositivo = Dispositivo.find(params[:dispositivo_id])  # linha inserida
    #@evento = Evento.new(evento_params)                      # linha anterior
    @evento = @dispositivo.eventos.create(evento_params)      # linha alterada

    respond_to do |format|
      if @evento.save
        # prox linha alterada @evento para @dispositivo, a resp volta pag dispositivo
        format.html { redirect_to @dispositivo, notice: 'Evento was successfully created.' }
        format.json { render :show, status: :created, location: @evento }
      else
        format.html { render :new }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /eventos/1
  # PATCH/PUT /eventos/1.json
  def update
    respond_to do |format|
      if @evento.update(evento_params)
        format.html { redirect_to @evento, notice: 'Evento was successfully updated.' }
        format.json { render :show, status: :ok, location: @evento }
      else
        format.html { render :edit }
        format.json { render json: @evento.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /eventos/1
  # DELETE /eventos/1.json
  def destroy
    @evento.destroy
    respond_to do |format|
      format.html { redirect_to eventos_url, notice: 'Evento was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_evento
      @evento = Evento.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def evento_params
      params.require(:evento).permit(:dispositivo_id, :part_number, :tipo_evento, :valor_registrado, :mensagem_evento, :data, :hora, :ip_address_registrado)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/condominios_helper.rb
module CondominiosHelper
end

app/helpers/dispositivos_helper.rb
module DispositivosHelper
end

app/helpers/eventos_helper.rb
module EventosHelper
end

app/views/condominios/_form.html.erb
<%= form_for(@condominio) do |f| %>
  <% if @condominio.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@condominio.errors.count, "error") %> prohibited this condominio from being saved:</h2>

      <ul>
      <% @condominio.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :lat %><br>
    <%= f.text_field :lat %>
  </div>
  <div class="field">
    <%= f.label :long %><br>
    <%= f.text_field :long %>
  </div>
  <div class="field">
    <%= f.label :endereco %><br>
    <%= f.text_field :endereco %>
  </div>
  <div class="field">
    <%= f.label :bairro %><br>
    <%= f.text_field :bairro %>
  </div>
  <div class="field">
    <%= f.label :cidade %><br>
    <%= f.text_field :cidade %>
  </div>
  <div class="field">
    <%= f.label :estado %><br>
    <%= f.text_field :estado %>
  </div>
  <div class="field">
    <%= f.label :cep %><br>
    <%= f.text_field :cep %>
  </div>
  <div class="field">
    <%= f.label :cnpj %><br>
    <%= f.text_field :cnpj %>
  </div>
  <div class="field">
    <%= f.label :numero_contrato_atual %><br>
    <%= f.text_field :numero_contrato_atual %>
  </div>
  <div class="field">
    <%= f.label :website %><br>
    <%= f.text_field :website %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/condominios/edit.html.erb
<h1>Editing condominio</h1>

<%= render 'form' %>

<%= link_to 'Show', @condominio %> |
<%= link_to 'Back', condominios_path %>

app/views/condominios/index.html.erb
<h1>Listing condominios</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Lat</th>
      <th>Long</th>
      <th>Endereco</th>
      <th>Bairro</th>
      <th>Cidade</th>
      <th>Estado</th>
      <th>Cep</th>
      <th>Cnpj</th>
      <th>Numero contrato atual</th>
      <th>Website</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @condominios.each do |condominio| %>
      <tr>
        <td><%= condominio.nome %></td>
        <td><%= condominio.lat %></td>
        <td><%= condominio.long %></td>
        <td><%= condominio.endereco %></td>
        <td><%= condominio.bairro %></td>
        <td><%= condominio.cidade %></td>
        <td><%= condominio.estado %></td>
        <td><%= condominio.cep %></td>
        <td><%= condominio.cnpj %></td>
        <td><%= condominio.numero_contrato_atual %></td>
        <td><%= condominio.website %></td>
        <td><%= link_to 'Show', condominio %></td>
        <td><%= link_to 'Edit', edit_condominio_path(condominio) %></td>
        <td><%= link_to 'Destroy', condominio, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Condominio', new_condominio_path %>

app/views/condominios/new.html.erb
<h1>New condominio</h1>

<%= render 'form' %>

<%= link_to 'Back', condominios_path %>

app/views/condominios/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @condominio.nome %>
</p>

<p>
  <strong>Lat:</strong>
  <%= @condominio.lat %>
</p>

<p>
  <strong>Long:</strong>
  <%= @condominio.long %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @condominio.endereco %>
</p>

<p>
  <strong>Bairro:</strong>
  <%= @condominio.bairro %>
</p>

<p>
  <strong>Cidade:</strong>
  <%= @condominio.cidade %>
</p>

<p>
  <strong>Estado:</strong>
  <%= @condominio.estado %>
</p>

<p>
  <strong>Cep:</strong>
  <%= @condominio.cep %>
</p>

<p>
  <strong>Cnpj:</strong>
  <%= @condominio.cnpj %>
</p>

<p>
  <strong>Numero contrato atual:</strong>
  <%= @condominio.numero_contrato_atual %>
</p>

<p>
  <strong>Website:</strong>
  <%= @condominio.website %>
</p>


<!--
  Este é um código inserido para associar todos os dispositivos ao seu condominio
  inclue divisao e um form para capturar novo dispositivo.
-->

<h2>Dispositivos</h2>
<div id="Dispositivos">
    <% @condominio.dispositivos.each do |dispositivo| %>
        <%= div_for dispositivo do %>
        <p>
           
            <%= h(dispositivo.nome) %>
        </p>
    <% end %>
<% end %>
</div>

<%= form_for([@condominio, Dispositivo.new]) do |f| %>
   <p><%= f.label :nome, "New Dispositivo" %><br />
      <%= f.text_area :nome %>
   </p>
   <p><%= f.submit "Add Dispositivo" %></p>
<% end %>


<!--
  fim do código inserido.
-->


<%= link_to 'Edit', edit_condominio_path(@condominio) %> |
<%= link_to 'Back', condominios_path %>

app/views/dispositivos/_form.html.erb
<%= form_for(@dispositivo) do |f| %>
  <% if @dispositivo.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@dispositivo.errors.count, "error") %> prohibited this dispositivo from being saved:</h2>

      <ul>
      <% @dispositivo.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :condominio_id %><br>
    <%= f.number_field :condominio_id %>
  </div>
  <div class="field">
    <%= f.label :part_number %><br>
    <%= f.text_field :part_number %>
  </div>
  <div class="field">
    <%= f.label :nome %><br>
    <%= f.text_field :nome %>
  </div>
  <div class="field">
    <%= f.label :fabricante %><br>
    <%= f.text_field :fabricante %>
  </div>
  <div class="field">
    <%= f.label :zonas %><br>
    <%= f.text_field :zonas %>
  </div>
  <div class="field">
    <%= f.label :tipo_dispositivo %><br>
    <%= f.text_field :tipo_dispositivo %>
  </div>
  <div class="field">
    <%= f.label :trigger_alarme %><br>
    <%= f.number_field :trigger_alarme %>
  </div>
  <div class="field">
    <%= f.label :valor_limite_superior %><br>
    <%= f.number_field :valor_limite_superior %>
  </div>
  <div class="field">
    <%= f.label :valor_limite_inferior %><br>
    <%= f.number_field :valor_limite_inferior %>
  </div>
  <div class="field">
    <%= f.label :ip_address_dispositivo %><br>
    <%= f.text_field :ip_address_dispositivo %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/dispositivos/edit.html.erb
<h1>Editing dispositivo</h1>

<%= render 'form' %>

<%= link_to 'Show', @dispositivo %> |
<%= link_to 'Back', dispositivos_path %>

app/views/dispositivos/index.html.erb
<h1>Listing dispositivos</h1>

<table>
  <thead>
    <tr>
      <th>Condominio</th>
      <th>Part number</th>
      <th>Nome</th>
      <th>Fabricante</th>
      <th>Zonas</th>
      <th>Tipo dispositivo</th>
      <th>Trigger alarme</th>
      <th>Valor limite superior</th>
      <th>Valor limite inferior</th>
      <th>Ip address dispositivo</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @dispositivos.each do |dispositivo| %>
      <tr>
        <td><%= dispositivo.condominio_id %></td>
        <td><%= dispositivo.part_number %></td>
        <td><%= dispositivo.nome %></td>
        <td><%= dispositivo.fabricante %></td>
        <td><%= dispositivo.zonas %></td>
        <td><%= dispositivo.tipo_dispositivo %></td>
        <td><%= dispositivo.trigger_alarme %></td>
        <td><%= dispositivo.valor_limite_superior %></td>
        <td><%= dispositivo.valor_limite_inferior %></td>
        <td><%= dispositivo.ip_address_dispositivo %></td>
        <td><%= link_to 'Show', dispositivo %></td>
        <td><%= link_to 'Edit', edit_dispositivo_path(dispositivo) %></td>
        <td><%= link_to 'Destroy', dispositivo, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Dispositivo', new_dispositivo_path %>

app/views/dispositivos/new.html.erb
<h1>New dispositivo</h1>

<%= render 'form' %>

<%= link_to 'Back', dispositivos_path %>

app/views/dispositivos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Condominio:</strong>
  <%= @dispositivo.condominio_id %>
</p>

<p>
  <strong>Part number:</strong>
  <%= @dispositivo.part_number %>
</p>

<p>
  <strong>Nome:</strong>
  <%= @dispositivo.nome %>
</p>

<p>
  <strong>Fabricante:</strong>
  <%= @dispositivo.fabricante %>
</p>

<p>
  <strong>Zonas:</strong>
  <%= @dispositivo.zonas %>
</p>

<p>
  <strong>Tipo dispositivo:</strong>
  <%= @dispositivo.tipo_dispositivo %>
</p>

<p>
  <strong>Trigger alarme:</strong>
  <%= @dispositivo.trigger_alarme %>
</p>

<p>
  <strong>Valor limite superior:</strong>
  <%= @dispositivo.valor_limite_superior %>
</p>

<p>
  <strong>Valor limite inferior:</strong>
  <%= @dispositivo.valor_limite_inferior %>
</p>

<p>
  <strong>Ip address dispositivo:</strong>
  <%= @dispositivo.ip_address_dispositivo %>
</p>


<!--
  Este é um código inserido para associar todos os dispositivos ao seu condominio
  inclue divisao e um form para capturar novo dispositivo.
-->

<h2>Eventos</h2>
<div id="Eventos">
    <% @dispositivo.eventos.each do |evento| %>
        <%= div_for evento do %>
        <p>
           
            <%= h(evento.mensagem_evento) %>
        </p>
    <% end %>
<% end %>
</div>

<%= form_for([@dispositivo, Evento.new]) do |f| %>
   <p><%= f.label :mensagem_evento, "New Evento" %><br />
      <%= f.text_area :mensagem_evento %>
   </p>
   <p><%= f.submit "Add Evento" %></p>
<% end %>


<!--
  fim do código inserido.
-->








<%= link_to 'Edit', edit_dispositivo_path(@dispositivo) %> |
<%= link_to 'Back', dispositivos_path %>

app/views/eventos/_form.html.erb
<%= form_for(@evento) do |f| %>
  <% if @evento.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@evento.errors.count, "error") %> prohibited this evento from being saved:</h2>

      <ul>
      <% @evento.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :dispositivo_id %><br>
    <%= f.number_field :dispositivo_id %>
  </div>
  <div class="field">
    <%= f.label :part_number %><br>
    <%= f.text_field :part_number %>
  </div>
  <div class="field">
    <%= f.label :tipo_evento %><br>
    <%= f.text_field :tipo_evento %>
  </div>
  <div class="field">
    <%= f.label :valor_registrado %><br>
    <%= f.number_field :valor_registrado %>
  </div>
  <div class="field">
    <%= f.label :mensagem_evento %><br>
    <%= f.text_field :mensagem_evento %>
  </div>
  <div class="field">
    <%= f.label :data %><br>
    <%= f.text_field :data %>
  </div>
  <div class="field">
    <%= f.label :hora %><br>
    <%= f.text_field :hora %>
  </div>
  <div class="field">
    <%= f.label :ip_address_registrado %><br>
    <%= f.text_field :ip_address_registrado %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/eventos/edit.html.erb
<h1>Editing evento</h1>

<%= render 'form' %>

<%= link_to 'Show', @evento %> |
<%= link_to 'Back', eventos_path %>

app/views/eventos/index.html.erb
<h1>Listing eventos</h1>

<table>
  <thead>
    <tr>
      <th>Dispositivo</th>
      <th>Part number</th>
      <th>Tipo evento</th>
      <th>Valor registrado</th>
      <th>Mensagem evento</th>
      <th>Data</th>
      <th>Hora</th>
      <th>Ip address registrado</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @eventos.each do |evento| %>
      <tr>
        <td><%= evento.dispositivo_id %></td>
        <td><%= evento.part_number %></td>
        <td><%= evento.tipo_evento %></td>
        <td><%= evento.valor_registrado %></td>
        <td><%= evento.mensagem_evento %></td>
        <td><%= evento.data %></td>
        <td><%= evento.hora %></td>
        <td><%= evento.ip_address_registrado %></td>
        <td><%= link_to 'Show', evento %></td>
        <td><%= link_to 'Edit', edit_evento_path(evento) %></td>
        <td><%= link_to 'Destroy', evento, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Evento', new_evento_path %>

app/views/eventos/new.html.erb
<h1>New evento</h1>

<%= render 'form' %>

<%= link_to 'Back', eventos_path %>

app/views/eventos/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Dispositivo:</strong>
  <%= @evento.dispositivo_id %>
</p>

<p>
  <strong>Part number:</strong>
  <%= @evento.part_number %>
</p>

<p>
  <strong>Tipo evento:</strong>
  <%= @evento.tipo_evento %>
</p>

<p>
  <strong>Valor registrado:</strong>
  <%= @evento.valor_registrado %>
</p>

<p>
  <strong>Mensagem evento:</strong>
  <%= @evento.mensagem_evento %>
</p>

<p>
  <strong>Data:</strong>
  <%= @evento.data %>
</p>

<p>
  <strong>Hora:</strong>
  <%= @evento.hora %>
</p>

<p>
  <strong>Ip address registrado:</strong>
  <%= @evento.ip_address_registrado %>
</p>

<%= link_to 'Edit', edit_evento_path(@evento) %> |
<%= link_to 'Back', eventos_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
<head>
  
    <meta charset="utf-8">
    
    <!--
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    -->
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Smart Automation</title>
    <title>Smartweb</title>
    <title>Administração</title>
    
    <meta name='viewport' content='width=1200'>


    <!-- Bootstrap Core CSS -->
    <link href="http://smartautomation.com.br/css/bootstrap.css" rel="stylesheet">
	
    <!-- Custom CSS -->
    <link href="http://smartautomation.com.br/css/custom.css" rel="stylesheet">

	<link href="http://smartautomation.com.br/css/animacao1.css" rel="stylesheet">
    
	<link href="http://smartautomation.com.br/css/modern-business.css" rel="stylesheet">

  <!-- parte do Rails anterior a introducao do CSS -->
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>


<body>

<div id="classe" style="display:none;"></div>
<div id="classe_li" style="display:none;"></div>

    <!-- Page Content -->
    <div class="container">

        <!-- Portfolio Item Heading -->
        <div class="row">
            <div class="col-lg-12">
            	<a href="http://smartautomation.com.br/home">
            	<img src="http://smartautomation.com.br/images/logo.png" class="img-responsive" style="padding:20px 20px;">                
                </a>
		    </div>
        </div>
    <!-- Aparentemente falta div, mas ao colocar desformata a apresentacao -->

<!-- parte do Rails que coloca codigo -->
<%= yield %>

</body>
</html>